### ISSUE TITLE
automatic switch from dark theme to light theme after following a link

### ISSUE THREAD

**Issue by mjkj** [RoyalRoadL/RoyalRoadLegends#127]
I was following the author-link from [http://royalroadl.com/fiction/chapter/103027](url) to [http://www.royalroadl.com/fiction/9163](url) and loading this it ended up displaying in the light theme instead of the usual dark theme I have.

This happened both with my mobile and on my computer.

Other chapters and story landing pages I accessed via the bookmark page were not affected.

Edit: It also changed the size / font setting I usually have once I accessed the chapter at the computer

**Comment by progandy** [comment]
Maybe the setting is stored on a per-domain basis. You can try to set the theme for the page with and without "www".

**Comment by mjkj** [comment]
Ah, that could be it... Thank you for pointing that out.

The bookmarks use the same domain (with or without the www) as the bookmark page is - and since I am too lazy to type the www I usually have the one without.

Maybe that should be amended that regardless of the domain it should be the same.

**Comment by kanadaj** [comment]
Moved issue to internal task management
