### ISSUE TITLE
various points about New Comment Notification

### ISSUE THREAD

**Issue by Ultrabenosaurus** [RoyalRoadL/RoyalRoadLegends#129]
1) One of the first things I did when I registered for RRL all those ~years~months ago was to disable basically all emails that MyBB wanted to send me about stuff, like PMs and subscribed threads. It would be nice if the New Comment Notification system respected such settings, and did not default to sending out emails about every new comment to people who have turned off that option already.

2) Why are the only options Email and/or PM? Why not notifications? New comments don't require anything fancy, really, just a "New comment on xx chapter of yy fic" with a link to the latest comment and a link to dismiss without going to the chapter.

3) How do I set the default as "PM only" instead of the current "Email only" so that the next time I comment on a chapter I won't start getting more emails all over again?

![image](https://cloud.githubusercontent.com/assets/1901532/20499106/ddd1c4f8-b027-11e6-83a4-f19f1c4ee856.png)

4) Both links within the email that should take you to the new comment I am being notified of are incorrect; while they do have the querystring necessary for loading the correct comments page, they lack the anchor and so don't automatically scroll down to the comment.

5) The comment's HTML source is being shown full as plain text in the email, neither being filtered out nor rendered at all.

6) The email template needs correcting to work in Gmail, at least, as the default text is not wrapping correctly.

![image](https://cloud.githubusercontent.com/assets/1901532/20498945/1bb8bbe2-b027-11e6-9469-ac33c9d10520.png)

7) Slightly off-topic, I guess, but the fact the Settings link on the new main site (drop-down menu of your own username) links to UserCP is a little confusing, especially now you are adding settings to the new site that aren't just about prettifying chapters.

**Comment by kanadaj** [comment]
I'll need these points split into separate tickets. There have been changes regarding how these notifications are set up, can you check if there is still an issue with respecting the right settings for new comments?

**Comment by kanadaj** [comment]
Moved to internal task management.
