### ISSUE TITLE
No "top reviews" section on homepage

### ISSUE THREAD

**Issue by Edward-Castle** [RoyalRoadL/RoyalRoadLegends#18]
Other authors have already confessed that now they don't care about reviews at all.

Plus, readers who used to review fics, suddenly find themselves lacking proper motivation.

Not only that, it makes "The Group" a lot less relevant.

It was a good system for finding underdog awesome fics. =/

**Comment by Rewritebywhocares** [comment]
Seconded

**Comment by StormyTeacup** [comment]
I agree - it's a way for some fics to get recognized; this site has alot of fics on it - it's hard to get readers to find yours - reviews were a great way to encourage others to read your story and supplied a direct link off the front page your story. Please bring them back!
