### ISSUE TITLE
"Lastest Comment" section limiting to 20 comments, missing comments.

### ISSUE THREAD

**Issue by WizOfTime** [RoyalRoadL/RoyalRoadLegends#42]
I get in excess of 20 comments a day. The Latest Comments section is limited to 20 comments.

That means if I miss any comments in that section, I will have no way to look back and see what I missed, especially if the comments were from previous chapters, not without manually checking the comment section of every single chapter.

Please add pagination.

**Comment by kanadaj** [comment]
Added with the dashboard rework
