### ISSUE TITLE
plan to read stories won't be moved to reading

### ISSUE THREAD

**Issue by xtremeloldude** [RoyalRoadL/RoyalRoadLegends#63]
so whenever i try to add a story from my "read later" list to 'follow' it says on the fiction page that it's bookmarked but it stays in 'read later"
i'm unsure if updates will be shown on my bookmarked page since none of the stories have updated so far

**Comment by curvinho** [comment]
They should show up.
Try navigating back and seeing if you can't find then in other pages.

**Comment by xtremeloldude** [comment]
just discovered that they were properly bookmarked. However they're also still in the "read later list"
