### ISSUE TITLE
Size Settings

### ISSUE THREAD

**Issue by mjkj** [RoyalRoadL/RoyalRoadLegends#71]
The size settings for the story are a very nice feature which I use.

Though the rest of the text of the page stays tiny - this is especially annoying when trying to write or read a comment. Could you please adjust this - Thank you.

Label: Enhancement

**Comment by curvinho** [comment]
Where is the text tiny?
The only settings we allow changing are for the reader. Otherwise we'd have many more issues.

**Comment by mjkj** [comment]
As you can see here in the attached picture (TinyText, page http://royalroadl.com/fiction/chapter/96872(url)) the comments are tiny in comparison to the text though quotes are bigger again than the comments as you can see in the attached picture (BiggerQuote, page: http://royalroadl.com/fiction/chapter/96831(url))

![tinytext](https://cloud.githubusercontent.com/assets/22667034/19219507/7aa1db7c-8e15-11e6-8f9c-ae443db781ae.jpg)
![biggerquote](https://cloud.githubusercontent.com/assets/22667034/19219544/481d7b9c-8e16-11e6-91fe-9846ce2b240d.jpg)

**Comment by Ultrabenosaurus** [comment]
ALL HAIL COOKIES
