### ISSUE TITLE
Trouble with inserting videos and spoilers

### ISSUE THREAD

**Issue by DocteurNS** [RoyalRoadL/RoyalRoadLegends#75]
There's no problem with images, but both videos and spoilers don't seem to work. I can insert them just fine inside the text editor (although I've trouble adding the hidden content of the "spoiler") but when published it's like they were never there.

**Comment by Ultrabenosaurus** [comment]
I just tried inserting spoilers and it works fine. The first one I did via Preview Comment and the second I just posted without previewing, both display fine.
![spoilers](http://puu.sh/rDavF/38cc368296.jpg)

Though as @DocteurNS says, adding the actual content of a spoiler seems tricky. The only way I figured out how to do it so far is to write HTML into the source view, I can't work out how to add it in the editor.
