### ISSUE TITLE
Comment Source-Code View on Mobile does not resize properly

### ISSUE THREAD

**Issue by mjkj** [RoyalRoadL/RoyalRoadLegends#93]
On a phone, when commenting and switching to the source-code view if you turn the phone to portrait the source-code box does not resize but extents out of the display to the right (including the ok and cancel buttons)

Further more scrolling scrolls the background instead of the source-code box.

Last tried yesterday

Label: Bug? Enhancement?

**Comment by kanadaj** [comment]
Can you provide a screenshot about what this looks like in landscape mode?

**Comment by mjkj** [comment]
Yes, have here the landscape and the portrait screenshots:
![landscape](https://cloud.githubusercontent.com/assets/22667034/19265720/86f9c8b6-8fa6-11e6-9622-d679f5d2e417.png)
![portrait](https://cloud.githubusercontent.com/assets/22667034/19265721/86feb498-8fa6-11e6-8b66-6ef086466688.png)

**Comment by kanadaj** [comment]
Sorry about the delay, does this also happen if you open source mode in portrait mode in the first place?

**Comment by mjkj** [comment]
Yes, that was opened in portrait. But if I open it in landscape it just shows a line (see screenshots below)

![screenshot_landscape](https://cloud.githubusercontent.com/assets/22667034/19552914/49398b52-96b2-11e6-8745-cc407cca415f.png)
![screenshot_portrait](https://cloud.githubusercontent.com/assets/22667034/19552913/49363e66-96b2-11e6-863f-76da53eb362f.png)
